server:
  port: 9101

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    maxThreadsForPeerReplication: 0

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false