server:
  port: 9101

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    maxThreadsForPeerReplication: 0

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

logging.level.com.netflix.config.sources.URLConfigurationSource: ERROR