server:
  port: 9102
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9101/eureka/}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-user
          uri: lb://MS-USER
          predicates:
            - Path=/api-user/**
        - id: ms-product
          uri: lb://MS-PRODUCT
          predicates:
            - Path=/api-product/**
        - id: ms-order
          uri: lb://MS-ORDER
          predicates:
            - Path=/api-order/**,/api-item/**
        - id: ms-blog
          uri: lb://MS-BLOG
          predicates:
            - Path=/api-blog/**
        - id: ms-image
          uri: lb://MS-IMAGE
          predicates:
            - Path=/api-image/**

okta:
  oauth2:
    issuer: https://dev-4559045.okta.com/oauth2/default
    client-id: 0oa1d5784NKjarKnL5d6
    client-secret: s5pAwCMOIYOmhHWDmKhQ894rHH_mnwwQIGvuhXJ4
    rolesClaim: groups
    audience: api://default

logging.level.com.netflix.config.sources.URLConfigurationSource: ERROR