eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9101/eureka/}

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-user
          uri: lb://MS-USER
          predicates:
            - Path=/api-user/**

okta:
  oauth2:
    issuer: https://dev-4559045.okta.com/oauth2/default
    client-id: 0oa1d5784NKjarKnL5d6
    client-secret: s5pAwCMOIYOmhHWDmKhQ894rHH_mnwwQIGvuhXJ4