eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9101/eureka/}

spring:
  cloud:
    gateway:
      routes:
      - id: ms-user
        uri: lb://MS-USER
        predicates:
        - Path=/api/user/**
      discovery:
        locator:
          lowerCaseServiceId: true
    loadbalancer:
      ribbon:
        enabled: false