product-configs:
  productsLimit: 2

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9101/eureka/}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    sql-script-encoding: UTF-8
    schema: classpath:schema/shop.sql
    # driverClassName: org.h2.Driver
    # url: jdbc:h2:file:./holitor-data/data;DB_CLOSE_ON_EXIT=FALSE

#Disable batch job's auto start 
spring.batch.job.enabled: false
spring.main.banner-mode: off

okta:
  oauth2:
    issuer: https://dev-4559045.okta.com/oauth2/default
    audience: api://default

logging.level.com.netflix.config.sources.URLConfigurationSource: ERROR

server.error.include-message: always