product-configs:
  productsLimit: 2

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9101/eureka/}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  h2:
    console:
      enabled: true
  # datasource:
  #   url: jdbc:h2:mem:testdb
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./holitor-data/data;DB_CLOSE_ON_EXIT=FALSE

okta:
  oauth2:
    issuer: https://dev-4559045.okta.com/oauth2/default
    audience: api://default

logging.level.com.netflix.config.sources.URLConfigurationSource: ERROR