product-configs:
  productsLimit: 2

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9101/eureka/}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    sql-script-encoding: UTF-8

spring-batch.user-datas.path: holitor-back-spring/holitor-service/src/main/resources/batch/data/user
spring-batch.shop-datas.path: holitor-back-spring/holitor-service/src/main/resources/batch/data/shop
spring-batch.blog-datas.path: holitor-back-spring/holitor-service/src/main/resources/batch/data/blog

okta:
  oauth2:
    issuer: https://dev-4559045.okta.com/oauth2/default
    audience: api://default

logging.level.com.netflix.config.sources.URLConfigurationSource: ERROR

server.error.include-message: always