eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9101/eureka/}

product-configs:
  productsLimit: 2

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

okta:
  oauth2:
    issuer: https://dev-4559045.okta.com/oauth2/default
    scopes: openid
    rolesClaim: groups
    audience: api://default

logging.level.com.netflix.config.sources.URLConfigurationSource: ERROR