spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-4559045.okta.com/oauth2/default
      client:
        registration:
          ms-user:
            provider: okta
            client-id: 0oa1ekuk8goIPhU8P5d6
            client-secret: Xkf0ACWwjAnIxW8WkSD4jEJtEh5I1sVqmiwwqhL_
            authorization-grant-type: client_credentials
            scopes: ms-user
            audience: api://default
        provider:
          okta:
            issuer-uri: https://dev-4559045.okta.com/oauth2/default

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9101/eureka/}

management:
  endpoints:
    web:
      exposure: 
        include: '*'

logging.level.com.netflix.config.sources.URLConfigurationSource: ERROR