spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9101/eureka/}

management:
  endpoints:
    web:
      exposure: 
        include: '*'

okta:
  oauth2:
    issuer: https://dev-4559045.okta.com/oauth2/default
    client-id: 0oa1d5784NKjarKnL5d6
    client-secret: s5pAwCMOIYOmhHWDmKhQ894rHH_mnwwQIGvuhXJ4